#! /bin/zsh

# Add JAVA_HOME
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# Set the path
PATH=/home/dfogelson/bin
PATH=$PATH:/home/dfogelson/.cargo/bin
PATH=$PATH:$JAVA_HOME
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/bin
PATH=$PATH::/sbin
PATH=$PATH:/bin
PATH=$PATH:/opt/cask/bin


# Node keeps moving this crap around and losing by clobal binaries
if [ -e /home/dfogelson/dots/node/node_modules/.bin ]
then
  PATH=$PATH:/home/dfogelson/dots/node/node_modules/.bin
fi

if [ -e /usr/lib/node_modules/DotsGlobalPackages/node_modules/.bin ]
then
  PATH=$PATH:/usr/lib/node_modules/DotsGlobalPackages/node_modules/.bin
fi



export PATH=$PATH

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="frog"

plugins=(git ubuntu command-not-found dircycle git-extras taskworrior pip node npm nvm pep8 grunt gradle docker docker-compose cp python pylint rust rsync kubectl sbt scala zsh_reload)

source $ZSH/oh-my-zsh.sh

export EDITOR=/usr/bin/emacs

# This is just a pain so I'm aliasing it
alias pip-update="pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U"
alias dux="du -h --max-depth=1"
alias sdux="sudo du -h --max-depth=1"
alias shup="~/dots/update.sh"
